# Generated by Django 5.2.12 on 2026-05-18 00:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inmate_number', models.CharField(max_length=50, unique=True)),
                ('last_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('name_suffix', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('solitary', 'Solitary'), ('lifer', 'Lifer')], max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_created_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='Prison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prison_type', models.CharField(choices=[('sci', 'SCI'), ('fci', 'FCI'), ('usp', 'USP'), ('city', 'City'), ('county', 'County'), ('fdc', 'FDC'), ('immigration_detention', 'Immigration Detention Facility'), ('boot_camp', 'Boot Camp'), ('rehab_facility', 'Rehab Facility')], max_length=200)),
                ('legacy_address', models.CharField(blank=True, max_length=200)),
                ('additional_mailing_headers', models.CharField(blank=True, max_length=200)),
                ('mailing_address', models.CharField(max_length=200)),
                ('mailing_city', models.CharField(max_length=200)),
                ('mailing_state', models.CharField(default='PA', max_length=50)),
                ('mailing_zipcode', models.CharField(max_length=200)),
                ('restrictions', models.TextField(blank=True)),
                ('legacy_id', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prison_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prison_modified_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PersonPrison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personprison_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prisons', to='app.person')),
                ('prison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='app.prison')),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postmark_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('stage1_complete_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('fulfilled_date', models.DateTimeField(blank=True, null=True)),
                ('counts_against_last_served', models.BooleanField(default=True)),
                ('workflow_stage', models.CharField(choices=[('stage1_complete', 'Stage 1 complete'), ('fulfilled', 'Fulfilled'), ('problem', 'Problem'), ('discarded', 'Discarded')], default='stage1_complete', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.person')),
                ('prison_requested_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letters_requested', to='app.prison')),
                ('prison_sent_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letters_fulfilled', to='app.prison')),
            ],
        ),
    ]
