# Generated by Django 5.2.12 on 2026-05-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_problemnote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemnote',
            old_name='notes',
            new_name='note',
        ),
    ]
