# Generated by Django 5.2.12 on 2026-05-25 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_notes_problemnote_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='problemnote',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_modified_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problemnote',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
