# Generated by Django 5.2.12 on 2026-06-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_problemnote_modified_by_problemnote_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='fulfillment_event_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='fulfillment_events',
            field=models.CharField(blank=True, choices=[('returned', 'Returned'), ('refulfilled', 'Refulfilled')], max_length=200),
        ),
        migrations.AddField(
            model_name='letter',
            name='refulfilled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='workflow_stage',
            field=models.CharField(choices=[('stage1_complete', 'Stage 1 complete'), ('fulfilled', 'Fulfilled'), ('problem', 'Problem'), ('discarded', 'Discarded'), ('returned', 'Returned'), ('refulfilled', 'Refulfilled')], default='stage1_complete', max_length=200),
        ),
    ]
