# Generated by Django 4.0.4 on 2022-04-30 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_personprison_rename_inmate_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='eligibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prison',
            name='city',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prison',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prison',
            name='notes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prison',
            name='prison_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prison',
            name='restrictions',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prison',
            name='state',
            field=models.CharField(default='PA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prison',
            name='street_address',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prison',
            name='zipcode',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField(blank=True, null=True)),
                ('date_processed', models.DateField(blank=True, null=True)),
                ('workflow_stage', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person')),
            ],
        ),
    ]
