# Generated by Django 5.2.12 on 2026-06-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_letter_fulfillment_event_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterissue',
            name='issue',
            field=models.CharField(choices=[('returned_package', 'Returned Package'), ('wrong_prison', 'Wrong prison in record'), ('other', 'Other')]),
        ),
        migrations.AlterField(
            model_name='personissue',
            name='issue',
            field=models.CharField(choices=[('wrong_prison', 'Wrong prison in record'), ('other', 'Other')]),
        ),
    ]
