# Generated by Django 4.0.4 on 2022-04-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_person_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprison',
            name='current',
            field=models.BooleanField(choices=[(True, 'Current'), (False, 'Not current')], default=False),
        ),
    ]
