# Generated by Django 4.0.4 on 2022-05-15 21:13

from django.db import migrations

def add_prisons(apps, schema_editor):
    Prison = apps.get_model('app', 'Prison')
    #open prisons file
    #add prisons
    pass

def remove_prisons(apps, schema_editor):
    #remove prisons
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_prison_external_id'),
    ]

    operations = [
            migrations.RunPython(add_prisons, remove_prisons)
    ]
