# Generated by Django 4.0.5 on 2022-07-13 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_person_last_sent_alter_letter_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='legacy_prison_id',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='processed_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 12, 23, 35, 59, 18786), null=True),
        ),
    ]
