# Generated by Django 4.0.5 on 2022-07-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_letter_modified_date_person_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prison',
            name='street_address',
        ),
        migrations.AddField(
            model_name='prison',
            name='legacy_street_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='prison',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='prison',
            name='prison_type',
            field=models.CharField(choices=[('sci', 'SCI'), ('fci', 'FCI'), ('city', 'City'), ('county', 'County'), ('fdc', 'FDC'), ('immigration_detention', 'Immigration Detention Facility'), ('boot_camp', 'Boot Camp')], max_length=200),
        ),
        migrations.AlterField(
            model_name='prison',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='prison',
            name='zipcode',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
