# Generated by Django 4.0.5 on 2022-07-31 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_prison_street_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prison',
            old_name='legacy_street_address',
            new_name='street_address',
        ),
    ]
