# Generated by Django 4.0.5 on 2022-08-08 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0030_alter_person_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_created_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
