# Generated by Django 4.0.5 on 2022-08-08 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0032_letter_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='prison',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prison_modified_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
