# Generated by Django 4.1.2 on 2022-10-24 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_rename_processed_date_letter_stage1_complete_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letter",
            name="awaiting_fulfillment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="letter",
            name="fulfilled_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="letter",
            name="stage1_complete_date",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
