# Generated by Django 4.1.2 on 2022-11-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0041_remove_person_eligibility_bool_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prison",
            name="mailing_address",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="prison",
            name="mailing_city",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="prison",
            name="mailing_state",
            field=models.CharField(default="PA", max_length=50),
        ),
        migrations.AlterField(
            model_name="prison",
            name="mailing_zipcode",
            field=models.CharField(max_length=200),
        ),
    ]
