# Generated by Django 4.1.2 on 2022-11-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0042_alter_prison_mailing_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prison",
            name="legacy_id",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
