# Generated by Django 4.2.15 on 2024-08-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0051_letter_counts_against_last_served"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prison",
            name="prison_type",
            field=models.CharField(
                choices=[
                    ("sci", "SCI"),
                    ("fci", "FCI"),
                    ("usp", "USP"),
                    ("city", "City"),
                    ("county", "County"),
                    ("fdc", "FDC"),
                    ("immigration_detention", "Immigration Detention Facility"),
                    ("boot_camp", "Boot Camp"),
                    ("rehab_facility", "Rehab Facility"),
                ],
                max_length=200,
            ),
        ),
    ]
