# Generated by Django 4.2.20 on 2025-05-04 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0052_alter_prison_prison_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="legacy_last_served_date",
        ),
        migrations.RemoveField(
            model_name="person",
            name="legacy_prison_id",
        ),
        migrations.AddField(
            model_name="letter",
            name="prison_requested_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="letters_requested",
                to="app.prison",
            ),
        ),
        migrations.AlterField(
            model_name="letter",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="letter",
            name="person",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.person"
            ),
        ),
        migrations.AlterField(
            model_name="letter",
            name="prison_sent_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="letters_fulfilled",
                to="app.prison",
            ),
        ),
        migrations.AlterField(
            model_name="prison",
            name="accepts_books",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="prison",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="prison",
            name="restrictions",
            field=models.TextField(blank=True),
        ),
    ]
