# Generated by Django 5.2.1 on 2025-08-17 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0055_alter_personprison_prison"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personprison",
            name="prison",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="people",
                to="app.prison",
            ),
        ),
    ]
