services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: prison_book_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: >
      sh -c "poetry run python manage.py migrate &&
             poetry run python manage.py collectstatic --noinput &&
             poetry run python manage.py shell -c \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', 'admin@localhost', 'admin')\" &&
             poetry run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      - db

volumes:
  pgdata: