# Generated by Django 5.2.12 on 2026-05-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomAuth', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_contributor',
            field=models.BooleanField(default=False),
        ),
    ]
