# Generated by Django 5.2.12 on 2026-05-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomAuth', '0003_user_is_contributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_contributor',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into the contributor-facing site.'),
        ),
    ]
