# Generated by Django 5.2.12 on 2026-06-08 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomAuth', '0004_remove_user_username_alter_user_is_contributor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('change_active', "Can change a user's active status"), ('change_is_contrib', "Can change a user's contributor status"), ('change_is_staff', "Can change a user's staff status")]},
        ),
    ]
