# Generated by Django 5.2.12 on 2026-06-08 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomAuth', '0005_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('change_is_active', "Can change a user's active status"), ('change_is_contrib', "Can change a user's contributor status"), ('change_is_staff', "Can change a user's staff status")]},
        ),
    ]
