# Generated by Django 4.0.4 on 2022-04-23 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InmatePrison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=False)),
                ('inmate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prisons', to='app.inmate')),
                ('prison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmates', to='app.prison')),
            ],
        ),
    ]
