# Generated by Django 4.0.4 on 2022-04-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_inmate_id_inmate_inmate_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmate',
            name='last_sent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmate',
            name='package_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
