# Generated by Django 4.0.4 on 2022-04-30 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_inmate_options_inmate_pending_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonPrison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Inmate',
            new_name='Person',
        ),
        migrations.DeleteModel(
            name='InmatePrison',
        ),
        migrations.AddField(
            model_name='personprison',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prisons', to='app.person'),
        ),
        migrations.AddField(
            model_name='personprison',
            name='prison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='app.prison'),
        ),
    ]
