# Generated by Django 4.0.4 on 2022-04-30 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_person_eligibility_person_first_name_prison_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('-pending_letter',), 'verbose_name_plural': 'people'},
        ),
    ]
