# Generated by Django 4.0.5 on 2022-06-12 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_external_id_prison_legacy_id_and_more'),
        ('app', '0017_auto_20220515_1737'),
    ]

    operations = [
    ]
