# Generated by Django 4.0.5 on 2022-07-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_merge_20220612_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'people'},
        ),
        migrations.RenameField(
            model_name='letter',
            old_name='date_processed',
            new_name='awaiting_fulfillment_date',
        ),
        migrations.RenameField(
            model_name='letter',
            old_name='date_received',
            new_name='fulfilled_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='eligibility',
        ),
        migrations.RemoveField(
            model_name='person',
            name='package_count',
        ),
        migrations.RemoveField(
            model_name='person',
            name='pending_letter',
        ),
        migrations.AddField(
            model_name='letter',
            name='postmark_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='processed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
