# Generated by Django 4.0.5 on 2022-07-13 03:33

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0019_alter_person_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='last_sent',
        ),
        migrations.AlterField(
            model_name='letter',
            name='created_by',
            field=models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_created_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='letter',
            name='modified_by',
            field=models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_modified_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='letter',
            name='processed_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 12, 23, 33, 23, 554343), null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='workflow_stage',
            field=models.CharField(choices=[('processed', 'Processed'), ('awaiting_fulfillment', 'Awaiting fulfillment'), ('fulfilled', 'Fulfilled')], default='processed', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_by',
            field=models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_created_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='modified_by',
            field=models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_modified_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
