# Generated by Django 4.0.5 on 2022-07-31 04:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_person_legacy_last_served_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='processed_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='prison',
            name='legacy_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
