# Generated by Django 4.0.5 on 2022-07-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_letter_processed_date_alter_prison_legacy_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='person',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(blank=True, choices=[('solitary', 'Solitary'), ('lifer', 'Lifer')], max_length=200),
        ),
        migrations.AlterField(
            model_name='letter',
            name='workflow_stage',
            field=models.CharField(choices=[('processed', 'Processed'), ('awaiting_fulfillment', 'Awaiting fulfillment'), ('fulfilled', 'Fulfilled'), ('just_pada', 'Just PADA'), ('problem', 'Problem')], default='processed', max_length=200),
        ),
        migrations.AlterField(
            model_name='prison',
            name='prison_type',
            field=models.CharField(choices=[('sci', 'SCI'), ('fci', 'FCI'), ('city', 'City'), ('county', 'County'), ('immigration_detention', 'Immigration Detention Facility'), ('boot_camp', 'Boot Camp')], max_length=200),
        ),
    ]
