# Generated by Django 4.0.5 on 2022-07-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_legacy_street_address_prison_street_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prison',
            old_name='city',
            new_name='legacy_address',
        ),
        migrations.RenameField(
            model_name='prison',
            old_name='street_address',
            new_name='mailing_address',
        ),
        migrations.RenameField(
            model_name='prison',
            old_name='zipcode',
            new_name='mailing_city',
        ),
        migrations.RenameField(
            model_name='prison',
            old_name='state',
            new_name='mailing_state',
        ),
        migrations.AddField(
            model_name='prison',
            name='mailing_zipcode',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
