# Generated by Django 4.0.5 on 2022-08-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_city_prison_legacy_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='inmate_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
