# Generated by Django 4.0.5 on 2022-08-08 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0029_remove_letter_modified_by_remove_person_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_created_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
