# Generated by Django 4.1.2 on 2022-10-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0037_alter_letter_awaiting_fulfillment_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="middle_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="person",
            name="name_suffix",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
