# Generated by Django 4.1.2 on 2022-11-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_person_middle_name_person_name_suffix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prison",
            name="prison_type",
            field=models.CharField(
                choices=[
                    ("sci", "SCI"),
                    ("fci", "FCI"),
                    ("usp", "USP"),
                    ("city", "City"),
                    ("county", "County"),
                    ("fdc", "FDC"),
                    ("immigration_detention", "Immigration Detention Facility"),
                    ("boot_camp", "Boot Camp"),
                ],
                max_length=200,
            ),
        ),
    ]
