# Generated by Django 4.1.2 on 2022-11-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0039_alter_prison_prison_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="eligibility_bool",
            field=models.BooleanField(default=True),
        ),
    ]
