# Generated by Django 4.1.2 on 2022-12-03 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0043_alter_prison_legacy_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="eligibility_status",
        ),
    ]
