# Generated by Django 4.1.2 on 2022-12-03 22:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0046_letter_prison_sent_to"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prison",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="letter",
            name="postmark_date",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
