# Generated by Django 4.1.2 on 2023-04-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0050_remove_letter_in_packing_pipeline_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="letter",
            name="counts_against_last_served",
            field=models.BooleanField(default=True),
        ),
    ]
