# Generated by Django 4.2.20 on 2025-05-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0053_remove_person_legacy_last_served_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
