# Generated by Django 4.0.5 on 2022-08-07 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_person_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='personprison',
            name='created_by',
        ),
    ]
