name: Backup databases
on:
  workflow_dispatch:
  schedule:
    # Runs Every day at 4:00am UTC
    - cron: "00 5 * * *"

jobs:
  backup-databases:
    name: Backup databases
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Start machine
        run: ./trigger-backup.sh
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
